---

resource_types:
  - name: npm-cache
    type: registry-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: 14

resources:
- name: source-code
  type: git
  source: &repo-source
    uri: https://github.com/Saudagar/serverless-dynamodb-curd.git
    branch: master 
- name: dependency-cache
  type: npm-cache
  icon: npm
  source:
    <<: *repo-source
    paths:
      - package.json     

jobs:
  - name: install
    plan:
    - get: source-code
      trigger: true
    - task: deploy-to-serverless
      params:
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
      file: source-code/ci/serverless-deploy.yml
